---
title: "Untitled"
author: "Lauren Ashlock"
date: "March 8, 2017"
output: html_document
---
### Linear Regression   
#### Summary Output
```{r}
linREGSUM <- function(x=runif(10), y=runif(10)){
  linMOD <- lm(y~x)
  myOUT <- summary(linMOD)
  return(myOUT)
}

linREGSUM()

##With dummy data

linREGSUM(x=rep(1,10), y=runif(10))

```

### Linear Regression   
#### Plot Output
```{r}
linREGPLT <- function(x=runif(10), y=runif(10)){
  linMOD <- lm(y~x)
  plot(y=y,x=x,pch=21,bg="lightblue",cex=2, main="Linear Regression", xlab="Generations of Exposure", ylab="Fecundity")
abline(linMOD, add=TRUE)
}

linREGPLT()

##With dummy data

linREGPLT(x=runif(10), y=runif(10))
```

### ANOVA   
#### Summary Output

```{r}

aovSUM <- function(x=as.factor(rep(c("Control","Toxic"),each=5)), y=c(rgamma(5,shape=5,scale=5),rgamma(5,shape=5,scale=10))){
  aovMOD <- aov(y~x)
  myOUT <- summary(aovMOD)
  return(myOUT)
}

aovSUM()

##With dummy data

aovSUM(x=as.factor(rep(c("Maine","New Jersey"),each=5)), y=c(rgamma(8,shape=5,scale=5),rgamma(2,shape=5,scale=10)))

```

### ANOVA
####Plot Output

```{r}

aovPLT <- function(x=as.factor(rep(c("Control","Toxic"),each=5)), y=c(rgamma(5,shape=5,scale=5),rgamma(5,shape=5,scale=10))){
  aovMOD <- aov(y~x)
  boxplot(y~x,col=c("darkolivegreen1","darkgreen"), ylab="Fecundity")
}

aovPLT()

##With dummy data

aovPLT(x=as.factor(rep(c("Maine","New Jersey"),each=5)), y=c(rgamma(8,shape=5,scale=5),rgamma(2,shape=5,scale=10)))

```


###Contingency Table
####Summary Output

```{r}
ContingencySUM <- function(dataMATRIX= rbind(c(90,98,89), c(70,60,20))){
  rownames(dataMATRIX) <- c("Control","Toxic")
  colnames(dataMATRIX) <-c("LowTOX",
                         "MedTOX",
                         "HighTOX")
  myOUT <- print(chisq.test(dataMATRIX))
  return(myOUT)
}

ContingencySUM()

##With dummy data

ContingencySUM(dataMATRIX = rbind(c(87,66, 77), c(66, 44, 23)))

```


###Contingency Table
#### Plot Output

```{r}
ContingencyPLT <- function(dataMATRIX= rbind(c(90,98,89), c(70,60,20))){
  rownames(dataMATRIX) <- c("Control","Toxic")
  colnames(dataMATRIX) <-c("LowTOX",
                         "MedTOX",
                         "HighTOX")
  barplot(height=dataMATRIX,
        beside=TRUE,
        col=c("darkolivegreen1","darkgreen"), ylim=c(0,max(colSums(dataMATRIX))), legend = rownames(dataMATRIX),args.legend=list(
      x=ncol(dataMATRIX) + 3,
      y=max(colSums(dataMATRIX)),
      bty = "n"
    ))
}

ContingencyPLT()

##With dummy data

ContingencySUM(dataMATRIX = rbind(c(87,66, 77), c(66, 44, 23)))
```

###Logistic Regression
####Summary Output
```{r}
LogisticSUM <- function(xVar, yVar){
  xVar <- rgamma(n=20,shape=5,scale=5)
yVar <- rbinom(n=20,size=1,p=0.5)
dataFrame <- data.frame(xVar,yVar)
logRegMod <- glm(yVar ~ xVar,
                 data=dataFrame,
                 family=binomial(link="logit"))
summary(logRegMod)
}

LogisticSUM()

## With dummy data
LogisticSUM(c(rgamma(n=100,shape=7, scale=1)), c(rbinom(n=100,size=1,p=0.2)))

```

###Logistic Regression
####Plot Output
```{r}
LogisticPLT <- function(xVar, yVar){
  xVar <- rgamma(n=20,shape=5,scale=5)
yVar <- rbinom(n=20,size=1,p=0.5)
dataFrame <- data.frame(xVar,yVar)
logRegMod <- glm(yVar ~ xVar,
                 data=dataFrame,
                 family=binomial(link="logit"))
plot(x=dataFrame$xVar, y=dataFrame$yVar,pch=21,bg="gray31",cex=2, xlab = "Treatment Days", ylab = "Survival", main = "Toxic Algal Survival")
curve(predict(logRegMod,data.frame(xVar=x),type="response"),add=TRUE,lwd=2)
}

LogisticPLT()

## With dummy data
LogisticPLT(c(rgamma(n=100,shape=7, scale=1)), c(rbinom(n=100,size=1,p=0.8)))



```

